//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WeighServiceSoap")]
    public interface WeighServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetWeight", ReplyAction="*")]
        RWService.ServiceReference.SetWeightResponse SetWeight(RWService.ServiceReference.SetWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<RWService.ServiceReference.SetWeightResponse> SetWeightAsync(RWService.ServiceReference.SetWeightRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 id 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeight", ReplyAction="*")]
        RWService.ServiceReference.GetWeightResponse GetWeight(RWService.ServiceReference.GetWeightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeight", ReplyAction="*")]
        System.Threading.Tasks.Task<RWService.ServiceReference.GetWeightResponse> GetWeightAsync(RWService.ServiceReference.GetWeightRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetWeightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetWeight", Namespace="http://tempuri.org/", Order=0)]
        public RWService.ServiceReference.SetWeightRequestBody Body;
        
        public SetWeightRequest() {
        }
        
        public SetWeightRequest(RWService.ServiceReference.SetWeightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetWeightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float weight;
        
        public SetWeightRequestBody() {
        }
        
        public SetWeightRequestBody(string id, float weight) {
            this.id = id;
            this.weight = weight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetWeightResponse", Namespace="http://tempuri.org/", Order=0)]
        public RWService.ServiceReference.SetWeightResponseBody Body;
        
        public SetWeightResponse() {
        }
        
        public SetWeightResponse(RWService.ServiceReference.SetWeightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetWeightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetWeightResult;
        
        public SetWeightResponseBody() {
        }
        
        public SetWeightResponseBody(int SetWeightResult) {
            this.SetWeightResult = SetWeightResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeight", Namespace="http://tempuri.org/", Order=0)]
        public RWService.ServiceReference.GetWeightRequestBody Body;
        
        public GetWeightRequest() {
        }
        
        public GetWeightRequest(RWService.ServiceReference.GetWeightRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeightRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetWeightRequestBody() {
        }
        
        public GetWeightRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeightResponse", Namespace="http://tempuri.org/", Order=0)]
        public RWService.ServiceReference.GetWeightResponseBody Body;
        
        public GetWeightResponse() {
        }
        
        public GetWeightResponse(RWService.ServiceReference.GetWeightResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeightResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float GetWeightResult;
        
        public GetWeightResponseBody() {
        }
        
        public GetWeightResponseBody(float GetWeightResult) {
            this.GetWeightResult = GetWeightResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeighServiceSoapChannel : RWService.ServiceReference.WeighServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeighServiceSoapClient : System.ServiceModel.ClientBase<RWService.ServiceReference.WeighServiceSoap>, RWService.ServiceReference.WeighServiceSoap {
        
        public WeighServiceSoapClient() {
        }
        
        public WeighServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeighServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeighServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeighServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RWService.ServiceReference.SetWeightResponse RWService.ServiceReference.WeighServiceSoap.SetWeight(RWService.ServiceReference.SetWeightRequest request) {
            return base.Channel.SetWeight(request);
        }
        
        public int SetWeight(string id, float weight) {
            RWService.ServiceReference.SetWeightRequest inValue = new RWService.ServiceReference.SetWeightRequest();
            inValue.Body = new RWService.ServiceReference.SetWeightRequestBody();
            inValue.Body.id = id;
            inValue.Body.weight = weight;
            RWService.ServiceReference.SetWeightResponse retVal = ((RWService.ServiceReference.WeighServiceSoap)(this)).SetWeight(inValue);
            return retVal.Body.SetWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RWService.ServiceReference.SetWeightResponse> RWService.ServiceReference.WeighServiceSoap.SetWeightAsync(RWService.ServiceReference.SetWeightRequest request) {
            return base.Channel.SetWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<RWService.ServiceReference.SetWeightResponse> SetWeightAsync(string id, float weight) {
            RWService.ServiceReference.SetWeightRequest inValue = new RWService.ServiceReference.SetWeightRequest();
            inValue.Body = new RWService.ServiceReference.SetWeightRequestBody();
            inValue.Body.id = id;
            inValue.Body.weight = weight;
            return ((RWService.ServiceReference.WeighServiceSoap)(this)).SetWeightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RWService.ServiceReference.GetWeightResponse RWService.ServiceReference.WeighServiceSoap.GetWeight(RWService.ServiceReference.GetWeightRequest request) {
            return base.Channel.GetWeight(request);
        }
        
        public float GetWeight(string id) {
            RWService.ServiceReference.GetWeightRequest inValue = new RWService.ServiceReference.GetWeightRequest();
            inValue.Body = new RWService.ServiceReference.GetWeightRequestBody();
            inValue.Body.id = id;
            RWService.ServiceReference.GetWeightResponse retVal = ((RWService.ServiceReference.WeighServiceSoap)(this)).GetWeight(inValue);
            return retVal.Body.GetWeightResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RWService.ServiceReference.GetWeightResponse> RWService.ServiceReference.WeighServiceSoap.GetWeightAsync(RWService.ServiceReference.GetWeightRequest request) {
            return base.Channel.GetWeightAsync(request);
        }
        
        public System.Threading.Tasks.Task<RWService.ServiceReference.GetWeightResponse> GetWeightAsync(string id) {
            RWService.ServiceReference.GetWeightRequest inValue = new RWService.ServiceReference.GetWeightRequest();
            inValue.Body = new RWService.ServiceReference.GetWeightRequestBody();
            inValue.Body.id = id;
            return ((RWService.ServiceReference.WeighServiceSoap)(this)).GetWeightAsync(inValue);
        }
    }
}
